apiVersion: v1
kind: Service
metadata:
  name: todolist-demo
  namespace: production
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: todolist-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-demo
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todolist-demo
  template:
    metadata:
      labels:
        app: todolist-demo
    spec:
      containers:
      - name: todolist-demo
        image: cbrgm/todolist-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todolist-demo-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - todolist.cbrgm.net
    secretName: todolist-demo-tls
  rules:
  - host: todolist.cbrgm.net
    http:
      paths:
      - path: /
        backend:
          serviceName: todolist-demo
          servicePort: 8080
